### ISSUE TITLE
Reconnect consumer on RabbitMQ restart 

### ISSUE THREAD

**Issue by zloyuser** [onliner/command-bus#7]

**Comment by zloyuser** [comment]
План деплоя:
1. Обновить проект `user.api`
2. Перезапустить воркеры `user.api`

**Comment by Zabavnyuk-Yauheny** [comment]
**Для QA:**
Методика тестирования:

1. Обновить user.api и перезапустить воркеры (Ветка `amqplib`)
2. В сервисном чате отправить сообщение и в таблице `user.events` проверить появление записи `Onliner\ServiceMessages\Chat\MessageCreated`
3. Рестартануть RabbitMQ командой `sudo systemctl restart rabbitmq-server.service`
4. Отправить сообщение в сервисный чат (не рестартуя воркеры после рестарта очереди). Запись `Onliner\ServiceMessages\Chat\MessageCreated` должна появиться

NOTE: Воркер пытается подключиться к очереди на протяжении 60 секунд с момента потери соединения

**Comment by Zabavnyuk-Yauheny** [comment]
Полноценно проверить не удалось из-за разности прод и дев окружения
Проверено:
 - Работоспособность сервисных чатов
 - При регистрации нового пользователя создается так же запись о нем в phpbb3.phpbb3_users

**Comment by Zabavnyuk-Yauheny** [comment]
Локально ОК

**Comment by Zabavnyuk-Yauheny** [comment]
На проде:
- Сервисные чаты создаются, сообщения отправляются и доходят
- При регистрации нового пользователя создается запись в phpbb3.phpbb3_users

**Comment by Zabavnyuk-Yauheny** [comment]
Прод ОК
